mode: "train" # "test"
dataset_name: "sPlot"
model:
  name: "RTranModel"
  input_dim: 27
  hidden_dim: 128
  output_dim: 3950
  backbone: "MLPBackbone"

training:
  learning_rate: 1e-3
  max_epochs: 20
  accelerator: "gpu"
  devices: 1

logger:
  project_name: "sPlotOpen"
  experiment_name: "ctran_splot_v0" # specify for training, or use to report test results
  experiment_key: "" # use to report test results,
  checkpoint_path: "./experiments_output"
  checkpoint_name: "last.ckpt"

data:
  base: "/network/projects/ecosystem-embeddings/sPlotOpen"
  train: "train_indices.npy"
  validation: "validation_indices.npy"
  test: "test_indices.npy"
  targets: "merged_species_occurrences.npy"

  worldclim_data_path: "worldclim_data.csv"
  soilgrid_data_path: "soilgrid_data.csv"

  species_occurrences_threshold: 100
  batch_size: 128

  species_list: "species_merge_duplicates.csv"

  partial_labels: True
  predict_family_of_species: -1
  maximum_known_labels_ratio: 0.75
