mode: "train" # "test"
dataset_name: "sPlot"
model:
  name: "Linear"
  input_dim: 27
  hidden_dim: 256
  num_classes: 3951
  backbone: ""

training:
  seed: 1337
  learning_rate: 1e-3
  max_epochs: 20
  accelerator: "gpu"
  devices: 1

logger:
  project_name: "sPlotOpen"
  experiment_name: "splot_linear" # specify for training, or use to report test results
  experiment_key: "" # use to report test results,
  checkpoint_path: "./model_checkpoints/1_sPlotOpen"
  checkpoint_name: ""

data:
  dataloader_to_use: "sPlotDataset"
  base: "/data/sPlotOpen"
  train: "train_indices.npy"
  validation: "validation_indices.npy"
  test: "test_indices.npy"
  targets: "merged_species_occurrences_v2.npy"

  batch_size: 64

  worldclim_data_path: "worldclim_data.csv"
  soilgrid_data_path: "soilgrid_data.csv"
  species_list: "species_merge_duplicates_v2.csv"
  species_occurrences_threshold: 100
  env_columns: [ 'bio_1', 'bio_2', 'bio_3', 'bio_4', 'bio_5', 'bio_6', 'bio_7', 'bio_8', 'bio_9', 'bio_10',
                 'bio_11', 'bio_12', 'bio_13', 'bio_14', 'bio_15', 'bio_16', 'bio_17', 'bio_18', 'bio_19',
                 "ORCDRC", "PHIHOX", "CECSOL", "BDTICM", "CLYPPT", "SLTPPT", "SNDPPT", "BLDFIE" ]

  partial_labels:
    use: False
    predict_family_of_species: -1