mode: "test" # "test"
dataset_name: "sPlot"
model:
  name: "CTranModel"
  input_dim: 27
  hidden_dim: 64
  output_dim: 3950
  backbone: "MLPBackbone"

training:
  batch_size: 64
  learning_rate: 1e-3
  max_epochs: 10
  accelerator: "gpu"
  devices: 1

logger:
  project_name: "sPlotOpen"
  experiment_name: "splot_cTran_model_v3_all_unknown`" # specify for training, or use to report test results
  experiment_key: "" # use to report test results,
  checkpoint_path: "./experiments_output"
  checkpoint_name: "last.ckpt"

data:
  dataloader_to_use: "sPlotMaskedDataset"
  base: "/network/projects/ecosystem-embeddings/sPlotOpen"
  train: "train_indices.npy"
  validation: "validation_indices.npy"
  test: "test_indices.npy"
  targets: "merged_species_occurrences.npy"

  worldclim_data_path: "worldclim_data.csv"
  soilgrid_data_path: "soilgrid_data.csv"

  species_occurrences_threshold: 100
  batch_size: 64

  species_list: "species_merge_duplicates.csv"
  env_columns: ['bio_1', 'bio_2', 'bio_3', 'bio_4', 'bio_5', 'bio_6', 'bio_7', 'bio_8', 'bio_9', 'bio_10',
         'bio_11', 'bio_12', 'bio_13', 'bio_14', 'bio_15', 'bio_16', 'bio_17', 'bio_18', 'bio_19',
        "ORCDRC", "PHIHOX", "CECSOL", "BDTICM", "CLYPPT", "SLTPPT", "SNDPPT", "BLDFIE"]

  partial_labels:
    use: True
    maximum_known_labels_ratio: 0
    predict_family_of_species: -1