#where to save checkpoints
save_path: "model_checkpoints/3_SatBirdxSatButterfly/satbirdxsatbutterfly_maxenet"

# load existing checkpoint for inference. If passing experiment folder instead (for multiple seeds), it will evaluate all of them.
# always use the best checkpoint
load_ckpt_path: "model_checkpoints/3_SatBirdxSatButterfly/satbirdxsatbutterfly_maxenet"
save_preds_path: ""

comet:
  project_name: "SDMPartialLabels"
  tags: [ "172butterfly_species", "50epochs", "satbird + satbutterflyv1 + satbutterflyv2" ]
  experiment_name: "satbirdxsatbutterfly_maxenet" # specify for training, or use to report test results
  experiment_key: "" # use to report test results,

dataloader_to_use: "SDMEnvDataset"

model:
  name: "Linear"
  input_dim: 1161
  hidden_dim: 256
  backbone:

training:
  seed: 1337
  lr: 0.0001
  max_epochs: 50
  accelerator: "cpu"

losses:
  criterion: "BCE"

# During testing, eval family of birds (0), or family of butterflies (1)
predict_family_of_species: -1

data:
  maxent_transform: True
  loaders:
    num_workers: 8
    batch_size: 128
    weighted_sampling: False

  #o you want to use environmental data (pedological and bioclimatic (low res) data) #ped" or "bioclim" or both or empty list
  env: [ 'bio_1', 'bio_2',
         'bio_3', 'bio_4', 'bio_5', 'bio_6', 'bio_7', 'bio_8', 'bio_9', 'bio_10',
         'bio_11', 'bio_12', 'bio_13', 'bio_14', 'bio_15', 'bio_16', 'bio_17',
         'bio_18', 'bio_19', 'bdticm', 'bldfie', 'cecsol', 'clyppt', 'orcdrc',
         'phihox', 'sltppt', 'sndppt' ]

  files:
    base: "/data"
    train: [ "SatBirdxSatButterfly/train_split.csv" ]
    val: [ "SatBirdxSatButterfly/valid_split.csv" ]
    test: [ "SatBirdxSatButterfly/test_split.csv" ]

    targets_file: [ "SatBird_data_v2/USA_summer/satbird_usa_summer_targets.pkl",
                    "SatButterfly/combined_SatButterfly_v1Andv2_targets.pkl" ]

    satbird_species_indices_path: "SatBird_data_v2/USA_summer/stats"

  # when combining two different taxa
  multi_taxa: True
  per_taxa_species_count: { "bird": 670, "butterfly": 172 }
  total_species: 842
  monitor_metric_1: "val_topk_bird"
  monitor_metric_2: "val_topk_butterfly"
