#where to save checkpoints
save_path: "multirun_experiments/final_satbirdxsatbutterfly/satbirdxsatbutterfly_maskedmlp_multi_ckpt_callback_v5"

# load existing checkpoint for inference. If passing experiment folder instead (for multiple seeds), it will evaluate all of them.
load_ckpt_path: "multirun_experiments/final_satbirdxsatbutterfly/satbirdxsatbutterfly_maskedmlp_multi_ckpt_callback_v5/"
save_preds_path: ""

dataloader_to_use: "SDMEnvMaskedDataset"

comet:
  project_name: "SDMPartialLabels"
  tags: [ "172butterfly_species", "bins=4", "50_epochs", "trainratio=0.75", "two_encoder_maskedmlp", "satbird + satbutterflyv1 + satbutterflyv2" ]
  experiment_name: "satbirdxsatbutterfly_maskedmlp_multi_ckpt_callback_v5" # specify for training, or use to report test results, TODO: also use to resume training
  experiment_key: "" # use to report test results,

model:
  name: "SimpleMLPMasked_v1"
  input_dim: 27
  hidden_dim: 256
  backbone:

training:
  seed: 1337
  lr: 0.0001
  max_epochs: 50
  accelerator: "cpu"

losses:
  criterion: "BCE"

partial_labels:
    use: true
    # mask known labels out of the loss (true or false)
    masked_loss: False
    # quantized mask (1 if all positives to 1, > 1 to indicate bins)
    quantized_mask_bins: 4
    # max ratio of unknown labels during training
    train_known_ratio: 0.75
    # what known ratios do we consider when testing
    eval_known_ratio: 0 # [1.0, 0.9, 0.8, 0.5]

# During testing, eval family of birds (0), or family of butterflies (1)
predict_family_of_species: -1

data:
  loaders:
    num_workers: 8
    batch_size: 128
    weighted_sampling: False

  #o you want to use environmental data (pedological and bioclimatic (low res) data) #ped" or "bioclim" or both or empty list
  env: ['bio_1', 'bio_2',
       'bio_3', 'bio_4', 'bio_5', 'bio_6', 'bio_7', 'bio_8', 'bio_9', 'bio_10',
       'bio_11', 'bio_12', 'bio_13', 'bio_14', 'bio_15', 'bio_16', 'bio_17',
       'bio_18', 'bio_19', 'bdticm', 'bldfie', 'cecsol', 'clyppt', 'orcdrc',
       'phihox', 'sltppt', 'sndppt']
  
  files:
    base: "/data"
    train: [ "SatBirdxSatButterfly/train_split.csv" ]
    val: [ "SatBirdxSatButterfly/valid_split.csv" ]
    test: [ "SatBirdxSatButterfly/test_split.csv" ]

    targets_file: [ "SatBird_data_v2/USA_summer/satbird_usa_summer_targets.pkl",
                    "SatButterfly/combined_SatButterfly_v1Andv2_targets.pkl" ]

    satbird_species_indices_path: "SatBird_data_v2/USA_summer/stats"
  # when combining two different taxa
  multi_taxa: True
  per_taxa_species_count: {"bird": 670, "butterfly": 172}
  total_species: 842
  monitor_metric_1: "val_topk_bird"
  monitor_metric_2: "val_topk_butterfly"
