#where to save checkpoints
save_path: "/network/projects/ecosystem-embeddings/SDMPartialLabels/CTran/birdxbutterflies_envencoder_hid512"

# load existing checkpoint for inference. If passing experiment folder instead (for multiple seeds), it will evaluate all of them.
load_ckpt_path: ""
save_preds_path: "" #"/network/scratch/h/hager.radi/ecosystem-embedding/baseline_resnet18_RGBNIR_ENV/preds_path"
log_comet: true

overfit_batches: 0.0
# maximum number of epochs to train for
max_epochs: 100
# base directory
base_dir: ""

comet:
  project_name: "SDMPartialLabels"
  tags: ["rtran", "172butterfly_species", "satbird+ satbutterflyv1 + satbutterflyv2"]
  experiment_name: "baseline_CTran_birdbutterfly_hid512_layers" # specify for training, or use to report test results, TODO: also use to resume training
  experiment_key: "" # use to report test results,

dataloader_to_use: "SDMEnvMaskedDataset"

experiment:
  #TASK and name should always be ebird_classifier --> maybe remove it 
  task: "ebird_classifier"
  name: "ebird_classifier"
  seed: 42
  module:
    #choose model : "resnet18" "resnet50" "inceptionv3" "linear" (just a linear model)
    model: "linear"
    #"linear" or "linear_net" for a 2 layer MLP
    fc: "linear"
    #use pretrained weights ( torchvision )
    pretrained: False
    # resume training from another model (transfer learning), set empty if training from scratch
    resume: ""
    freeze: False
    #initializes biases of the output layer sothat sigmoid(bias) = mean over the training set for each species
    init_bias: ""
    means_path: ""
    lr: 0.0001

Ctran:
    use: true
    # Resnet18 or Resnet50
    backbone: "SimpleMLPBackbone"
    # use ImageNet pretrained weights
    pretrained_backbone: False
    # size of hidden feature vector: should match the backbone output feature size (512 for Resnet18, 2048 for Resnet50)
    features_size: 512
    # mask known labels out of the loss (true or false)
    masked_loss: False
    # quantized mask (1 if all positives to 1, > 1 to indicate bins)
    quantized_mask_bins: 4
    # use positional encoding
    use_positional_encoding: True
    attention_layers: 3
    heads: 4
    dropout: 0.2
    # max ratio of unknown labels during training
    train_known_ratio: 0.75
    # what known ratios do we consider when testing
    eval_known_ratio: 0 # 0 or 1
    num_layers: 2


# eval family of birds (0), or family of butterflies (1)
predict_family_of_species: -1

optimizer: "AdamW"  #"Adam", "AdamW", "SGD"

losses:
#scale attribute is just for plotting if the values are very small
  criterion: "CE" #or MAE or MSE or Focal or RMSLE  (loss to choose for optim )

data:
  loaders:
    num_workers: 8
    batch_size: 128

  #o you want to use environmental data (pedological and bioclimatic (low res) data) #ped" or "bioclim" or both or empty list
  env: ['bio_1', 'bio_2',
       'bio_3', 'bio_4', 'bio_5', 'bio_6', 'bio_7', 'bio_8', 'bio_9', 'bio_10',
       'bio_11', 'bio_12', 'bio_13', 'bio_14', 'bio_15', 'bio_16', 'bio_17',
       'bio_18', 'bio_19', 'bdticm', 'bldfie', 'cecsol', 'clyppt', 'orcdrc',
       'phihox', 'sltppt', 'sndppt']
  
  files:
    base: "/network/projects/ecosystem-embeddings/"
    train: ["SatBirdButterfly/train_split_fillna.csv"]
    val: ["SatBirdButterfly/valid_split_fillna.csv"]
    test: ["SatBirdButterfly/test_split_fillna.csv"]

    targets_file: ["SatBird_data_v2/USA_summer/satbird_usa_summer_targets.pkl","SatButterfly_dataset/SatButterfly_v1/USA/butterfly_all_targets_v1.2.pkl","SatButterfly_dataset/SatButterfly_v2/USA/butterfly_all_targets_v1.2.pkl"]
    satbird_species_indices_path: "SatBird_data_v2/USA_summer/stats"

  multi_taxa: True
  per_taxa_species_count: [670, 172]
  total_species: 842
