#where to save checkpoints
save_path: "experiments_outputs/baseline_MLP_satbirdxsatbutterfly_v0"

# load existing checkpoint for inference. If passing experiment folder instead (for multiple seeds), it will evaluate all of them.
load_ckpt_path: ""
save_preds_path: ""

# maximum number of epochs to train for
max_epochs: 100
# base directory
base_dir: ""

comet:
  project_name: "SDMPartialLabels"
  tags: ["rtran", "172butterfly_species", "satbird+ satbutterflyv1 + satbutterflyv2"]
  experiment_name: "baseline_MLP_satbirdxsatbutterfly_v0" # specify for training, or use to report test results, TODO: also use to resume training
  experiment_key: "" # use to report test results,

dataloader_to_use: "SDMEnvCombinedDataset"

experiment:
  #TASK and name should always be ebird_classifier --> maybe remove it 
  task: "ebird_classifier"
  name: "ebird_classifier"
  seed: 42
  module:
    #choose model : "resnet18" "resnet50" "inceptionv3" "linear" (just a linear model)
    model: "MlpEncoder"
    #"linear" or "linear_net" for a 2 layer MLP
    fc: "linear"
    #use pretrained weights ( torchvision )
    pretrained: False
    # resume training from another model (transfer learning), set empty if training from scratch
    resume: ""
    freeze: False
    #initializes biases of the output layer sothat sigmoid(bias) = mean over the training set for each species
    init_bias: ""
    means_path: ""
    lr: 0.0001

Rtran:
    use: False
    # Resnet18 or Resnet50
    backbone: "MlpEncoder"
    # use ImageNet pretrained weights
    pretrained_backbone: False
    # size of hidden feature vector: should match the backbone output feature size (512 for Resnet18, 2048 for Resnet50)
    features_size: 512
    # mask known labels out of the loss (true or false)
    masked_loss: False
    # quantized mask (1 if all positives to 1, > 1 to indicate bins)
    quantized_mask_bins: 4
    # use positional encoding
    use_positional_encoding: True
    # use the actual regression labels as input to the model and multiply with the embeddings (true or false)
    scale_embeddings_by_labels: False
    # max ratio of unknown labels during training
    train_known_ratio: 0.75
    # what known ratios do we consider when testing
    eval_known_ratio: 0.0 # [1.0, 0.9, 0.8, 0.5]
    # should the known values be masked out of the reported metrics or no
    mask_eval_metrics: True

# eval family of birds (0), or family of butterflies (1)
predict_family_of_species: -1

data:
  loaders:
    num_workers: 8
    batch_size: 128

  #o you want to use environmental data (pedological and bioclimatic (low res) data) #ped" or "bioclim" or both or empty list
  env: ['bio_1', 'bio_2',
       'bio_3', 'bio_4', 'bio_5', 'bio_6', 'bio_7', 'bio_8', 'bio_9', 'bio_10',
       'bio_11', 'bio_12', 'bio_13', 'bio_14', 'bio_15', 'bio_16', 'bio_17',
       'bio_18', 'bio_19', 'bdticm', 'bldfie', 'cecsol', 'clyppt', 'orcdrc',
       'phihox', 'sltppt', 'sndppt']
  
  files:
    base: "/network/projects/ecosystem-embeddings/"
    train: ["SatBirdButterfly/bird_butterfly_train_env_fillna.csv"]
    val: ["SatBirdButterfly/bird_butterfly_valid_env_fillna.csv"]
    test: ["SatBirdButterfly/bird_butterfly_test_coloc_env_fillna.csv"]

    targets_folder: ["SatBird_data_v2/USA_summer/targets",
                     "SatButterfly_dataset/SatButterfly_v1/USA/butterfly_targets_v1.2",
                     "SatButterfly_dataset/SatButterfly_v2/USA/butterfly_targets_v1.2"]

    species_list: "/network/projects/ecosystem-embeddings/SatButterfly_v2/USA/species_list_USA_birds+butterflies.txt"

  species: [670, 172]
  species_eval:
  total_species: 842  #1271  # list if more than one family of species, otherwise, normal count
