#where to save checkpoints
save_path: "multirun_experiments/satbirdxsplots_ctran_v7"

# load existing checkpoint for inference. If passing experiment folder instead (for multiple seeds), it will evaluate all of them.
# always use the best checkpoint
load_ckpt_path: "multirun_experiments/satbirdxsplots_ctran_v7"
save_preds_path: ""

comet:
  project_name: "SDMPartialLabels"
  tags: [ "satbird + splots", "same_as_v2", "US_species_only", "bins=1", "train_ratio=0.75" ]
  experiment_name: "satbirdxsplots_ctran_v7" # specify for training, or use to report test results
  experiment_key: "" # use to report test results,

dataloader_to_use: "SDMEnvMaskedDataset"

model:
  name: "CTranModel"
  input_dim: 27
  hidden_dim: 256
  backbone: "SimpleMLPBackbone"
  n_backbone_layers: 2
  n_attention_layers: 3
  n_heads: 4
  dropout: 0.2

training:
  seed: 1337
  lr: 0.0001
  max_epochs: 50
  accelerator: "gpu"

losses:
  criterion: "BCE"

partial_labels:
    use: true
    # mask known labels out of the loss (true or false)
    masked_loss: False
    # quantized mask (1 if all positives to 1, > 1 to indicate bins)
    quantized_mask_bins: 1
    # max ratio of unknown labels during training
    train_known_ratio: 0.75
    # what known ratios do we consider when testing
    eval_known_ratio: 0 # [1.0, 0.9, 0.8, 0.5]

# During testing, eval family of birds (0), or family of plants (1)
predict_family_of_species: -1

data:
  loaders:
    num_workers: 8
    batch_size: 128
    weighted_sampling: False

  #o you want to use environmental data (pedological and bioclimatic (low res) data) #ped" or "bioclim" or both or empty list
  env: ['bio_1', 'bio_2',
       'bio_3', 'bio_4', 'bio_5', 'bio_6', 'bio_7', 'bio_8', 'bio_9', 'bio_10',
       'bio_11', 'bio_12', 'bio_13', 'bio_14', 'bio_15', 'bio_16', 'bio_17',
       'bio_18', 'bio_19', 'bdticm', 'bldfie', 'cecsol', 'clyppt', 'orcdrc',
       'phihox', 'sltppt', 'sndppt']
  
  files:
    base: "/data"
    train: [ "SatBirdxsPlotOpen/satbird_splots_train_split.csv" ]
    val: [ "SatBirdxsPlotOpen/satbird_splots_valid_split.csv" ]
    test: [ "SatBirdxsPlotOpen/satbird_splots_test_split.csv" ]

    # it has to be in this order as the keys in per_taxa_species_count
    targets_file: ["SatBird_data_v2/USA_summer/satbird_usa_summer_targets.pkl",
                   "SatBirdxsPlotOpen/sPlotOpen_targets_US_only.pkl" ] # target files follow the same format as SatBird (hotspotID: target_array)

    satbird_species_indices_path: "SatBird_data_v2/USA_summer/stats"
    #TODO: remove this and compute dynamically
    plant_test_species_indices_file: "SatBirdxsPlotOpen/plant_test_species_indices_US_only.npy"
    plant_val_species_indices_file: "SatBirdxsPlotOpen/plant_validation_species_indices_US_only.npy"

  # when combining two different taxa
  multi_taxa: True
  per_taxa_species_count: {"bird": 670, "plant": 607}
  total_species: 1277
  monitor_metric_1: "val_topk_bird"
  monitor_metric_2: "val_auc_plant"