#where to save checkpoints
save_path:
load_ckpt_path:
save_preds_path:

dataloader_to_use:

log_comet: true
comet:
  project_name:
  tags:
  experiment_name: "" # specify for training, or use to report test results, TODO: also use to resume training
  experiment_key: "" # use to report test results,

model:
  name:
  input_dim:
  hidden_dim:
  backbone:

training:
  seed: 1337
  lr:
  max_epochs: 50

partial_labels:
    use: false
    # mask known labels out of the loss (true or false)
    masked_loss: False
    # quantized mask (1 if all positives to 1, > 1 to indicate bins)
    quantized_mask_bins: 4
    # max ratio of unknown labels during training
    train_known_ratio: 0.75
    # what known ratios do we consider when testing
    eval_known_ratio: 0.0 # [1.0, 0.9, 0.8, 0.5]

data:
  loaders:
    num_workers: 8
    batch_size: 256

  #o you want to use environmental data (pedological and bioclimatic (low res) data) #ped" or "bioclim" or both or empty list
  env: ['bio_1', 'bio_2',
       'bio_3', 'bio_4', 'bio_5', 'bio_6', 'bio_7', 'bio_8', 'bio_9', 'bio_10',
       'bio_11', 'bio_12', 'bio_13', 'bio_14', 'bio_15', 'bio_16', 'bio_17',
       'bio_18', 'bio_19', 'bdticm', 'bldfie', 'cecsol', 'clyppt', 'orcdrc',
       'phihox', 'sltppt', 'sndppt']

  files:
    base:
    train:
    val:
    test:

    # it has to be in this order [bird, butterfly, colocated]
    targets_file:

    satbird_species_indices_path:

  # when combining two different taxa
  multi_taxa:
  per_taxa_species_count:
  total_species:

losses:
#scale attribute is just for plotting if the values are very small
  criterion: "CE" #or MAE or MSE  (loss to choosefor optim )

metrics:
  - name: ce
    ignore: True
    #weights on the cross entropy
    lambd_pres: 1
    lambd_abs: 1
    scale : 1
  - name: mae
    ignore: False
    scale: 10
  - name: nonzero_mae
    ignore: False
    scale: 10
  - name: mse
    ignore: False
    scale: 10
  - name: nonzero_mse
    ignore: False
    scale: 10
  - name: topk
    ignore: False
    scale: 1
  - name: topk2
    ignore: False
    scale: 1
  - name: r2
    ignore: True #False
    scale: 1
  - name: kl
    ignore: False
    scale : 1
  - name: accuracy
    ignore: True
    scale: 1
  - name: top10
    ignore: False
    scale: 1
  - name: top30
    ignore: False
    scale: 1
